apiVersion: v2
name: knot
description: |
  knot — self-hosted Confluence/Notion alternative.
  Multi-user collaborative knowledge base with CRDT-backed
  real-time editing.
type: application
version: 0.3.4
appVersion: "0.1.7"
home: https://github.com/trevex/knot
sources:
  - https://github.com/trevex/knot
maintainers:
  - name: christianhuening
icon: ""
keywords:
  - knot
  - wiki
  - collaboration
