{{- if and (not .Values.database.existingSecretName) (not .Values.session.existingSecretName) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knot.fullname" . }}
  labels:
    {{- include "knot.labels" . | nindent 4 }}
type: Opaque
stringData:
  KNOT_DATABASE_URL: {{ required "database.url or database.existingSecretName is required" .Values.database.url | quote }}
  KNOT_SESSION_KEY: {{ required "session.key or session.existingSecretName is required" .Values.session.key | quote }}
  {{- if and .Values.oidc.enabled .Values.oidc.clientSecret }}
  KNOT_OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
{{- end -}}
