// Code generated by tools/schemagen. DO NOT EDIT.

export const SCHEMA_VERSION = "0.1.0";

export const NODE_KINDS = [
  "doc",
  "paragraph",
  "heading",
  "blockquote",
  "code_block",
  "horizontal_rule",
  "bullet_list",
  "ordered_list",
  "list_item",
  "text",
  "hard_break",
  "excalidraw_board",
] as const;
export type NodeKind = (typeof NODE_KINDS)[number];

export const MARK_KINDS = [
  "bold",
  "italic",
  "code",
  "strike",
  "underline",
  "link",
] as const;
export type MarkKind = (typeof MARK_KINDS)[number];

export interface MarkMarkdownMeta {
  delimiter?: string;
  openTag?: string;
  closeTag?: string;
  noNesting?: boolean;
}

export const MARK_SERIALIZATION: Record<MarkKind, MarkMarkdownMeta> = {
  bold: { delimiter: "**", openTag: "", closeTag: "", noNesting: false },
  italic: { delimiter: "*", openTag: "", closeTag: "", noNesting: false },
  code: { delimiter: "`", openTag: "", closeTag: "", noNesting: true },
  strike: { delimiter: "~~", openTag: "", closeTag: "", noNesting: false },
  underline: { delimiter: "", openTag: "<u>", closeTag: "</u>", noNesting: false },
  link: { delimiter: "", openTag: "", closeTag: "", noNesting: false },
};
