// Code generated by tools/schemagen. DO NOT EDIT.

#![allow(dead_code)]

pub const SCHEMA_VERSION: &str = "0.1.0";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NodeKind {
    Doc,
    Paragraph,
    Heading,
    Blockquote,
    CodeBlock,
    HorizontalRule,
    BulletList,
    OrderedList,
    ListItem,
    Text,
    HardBreak,
    ExcalidrawBoard,
    Image,
    Attachment,
    Table,
    TableRow,
    TableCell,
    TableHeader,
}

impl NodeKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Doc => "doc",
            Self::Paragraph => "paragraph",
            Self::Heading => "heading",
            Self::Blockquote => "blockquote",
            Self::CodeBlock => "code_block",
            Self::HorizontalRule => "horizontal_rule",
            Self::BulletList => "bullet_list",
            Self::OrderedList => "ordered_list",
            Self::ListItem => "list_item",
            Self::Text => "text",
            Self::HardBreak => "hard_break",
            Self::ExcalidrawBoard => "excalidraw_board",
            Self::Image => "image",
            Self::Attachment => "attachment",
            Self::Table => "table",
            Self::TableRow => "table_row",
            Self::TableCell => "table_cell",
            Self::TableHeader => "table_header",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MarkKind {
    Bold,
    Italic,
    Code,
    Strike,
    Underline,
    Link,
}

impl MarkKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Bold => "bold",
            Self::Italic => "italic",
            Self::Code => "code",
            Self::Strike => "strike",
            Self::Underline => "underline",
            Self::Link => "link",
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct MarkMarkdownMeta {
    pub delimiter: &'static str,
    pub open_tag: &'static str,
    pub close_tag: &'static str,
    pub no_nesting: bool,
}

pub fn mark_serialization(kind: MarkKind) -> MarkMarkdownMeta {
    match kind {
        MarkKind::Bold => MarkMarkdownMeta { delimiter: "**", open_tag: "", close_tag: "", no_nesting: false },
        MarkKind::Italic => MarkMarkdownMeta { delimiter: "*", open_tag: "", close_tag: "", no_nesting: false },
        MarkKind::Code => MarkMarkdownMeta { delimiter: "`", open_tag: "", close_tag: "", no_nesting: true },
        MarkKind::Strike => MarkMarkdownMeta { delimiter: "~~", open_tag: "", close_tag: "", no_nesting: false },
        MarkKind::Underline => MarkMarkdownMeta { delimiter: "", open_tag: "<u>", close_tag: "</u>", no_nesting: false },
        MarkKind::Link => MarkMarkdownMeta { delimiter: "", open_tag: "", close_tag: "", no_nesting: false },
    }
}
